apiVersion: projectriff.io/v1
kind: Topic
metadata:
  name: words
---

apiVersion: projectriff.io/v1
kind: Topic
metadata:
  name: counts
---

apiVersion: projectriff.io/v1
kind: Function
metadata:
  name: counter
spec:
  protocol: http
  input: words
  output: counts
  container:
    image: projectriff/counter:1.0.0
