apiVersion: projectriff.io/v1
kind: Topic
metadata:
  name: counts
---

apiVersion: projectriff.io/v1
kind: Function
metadata:
  name: redis-writer
spec:
  protocol: http
  input: counts
  container:
    image: projectriff/redis-writer:1.0.0
    env:
    - name: REDIS_HOST
      value: counters-redis.default.svc.cluster.local
    - name: REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: counters-redis
          key: redis-password
